language: ruby

sudo: false

matrix:
  include:
    - rvm: 2.3.1
      script:
        - bundle exec danger
    - rvm: 2.3.1
    - rvm: 2.3.0
    - rvm: 2.2.5
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby-head
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2

bundler_args: --without development
