language: ruby

sudo: false

matrix:
  include:
    - rvm: 2.6.1
    - rvm: 2.6.0
    - rvm: 2.5.3
    - rvm: 2.5.2
    - rvm: 2.5.1
    - rvm: 2.5.0
    - rvm: 2.4.4
    - rvm: 2.4.3
    - rvm: 2.4.2
    - rvm: 2.4.1
    - rvm: 2.4.1
      script:
        - bundle exec danger
    - rvm: 2.3.6
    - rvm: 2.3.5
    - rvm: 2.3.4
    - rvm: 2.2.7
    - rvm: jruby-9.1.12.0
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2

before_install:
  - gem update --system
  - gem install bundler

bundler_args: --without development
