language: ruby

sudo: false

matrix:
  include:
    - rvm: 2.4.1
    - rvm: 2.4.1
      script:
        - bundle exec danger
    - rvm: jruby-9.1.12.0
    - rvm: jruby-head
    - rvm: 2.2.7
    - rvm: 2.3.4
    - rvm: rbx-2
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2

before_install:
  - gem update --system
  - gem install bundler

bundler_args: --without development
